services:
  db:
    image: postgres:16-alpine
    container_name: career_assistant_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: career_assistant_backend
    ports:
      - "8000:8000"
    volumes:
      - ../config.yaml:/app/config.yaml
      - ./migrations:/app/migrations
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: 