[project]
name = "career_assistant_backend"
version = "0.1.0"
description = "Backend for the Career Assistant project."
authors = [{ name = "Your Name", email = "your@email.com" }]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    "apscheduler>=3.11.0",
    "loguru>=0.7.3",
    "pydantic-settings-yaml>=0.2.0",
    "pydantic>=2.11.5",
    "pytelegrambotapi>=4.27.0",
    "tortoise-orm>=0.25.1",
]

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "A", "C4", "T20", "SIM", "PTH"]
ignore = ["E501"]

[tool.uv]
dev-dependencies = [
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
    "ruff>=0.11.13",
]
